---
version: '2'
services:
  rb1:
    build: ./rb1/
    command: "tail -f /dev/null"
    volumes:
      - ./rb1:/code
    ports:
      - "8000:80"
    networks:
       dock_net:
          ipv4_address: 127.0.0.3
    container_name: rb1

  rb2:
    build: ./rb2/
    command: "tail -f /dev/null"
    volumes:
      - ./rb2:/code
    ports:
      - "8001:80"
    networks:
        dock_net:
          ipv4_address: 127.0.0.4
    container_name: rb2

networks:
  dock_net:
    driver: bridge
    ipam:
     config:
       - subnet: "127.0.0.0/8"
         gateway: "127.0.0.1"

